[build]
  command = "npm run build"
  publish = "dist/public"

[[redirects]]
  from = "/camping"
  to = "https://camping.annaiapp.com"
  status = 301
  force = true

[[redirects]]
  from = "/camping/*"
  to = "https://camping.annaiapp.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
